### ISSUE TITLE
GET Request should go in a method

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenInstitute/np_config#7]
The GET request is being performed on the import of this file. This should be moved into a method

https://github.com/AllenInstitute/np_config/blob/27ce58284db12d63c8e8477556e0ef58a6f1f7f7/src/np_config/rigs.py#L68

**Comment by bjhardcastle** [comment]
https://github.com/AllenInstitute/np_config/commit/ca57312eae1b5a9751a0eaa594551b742b31961f
